### ISSUE TITLE
applist加载不出来~虽然没啥关系，我觉得是jar包作者的锅

### ISSUE THREAD

**Issue by imjonat** [leeeboo/awtrix-bilibili#1]
自己黑群晖docker了一下（已路由器翻），applist就是Loading Applist...
找了台新加坡主机手动撞了下，applist也是这样。。醉啦
第一次装，他家服务器就崩了。。。

> **但求jar包开源，共同维护**

**Comment by leeeboo** [comment]
可以正常加载，目前我的这个插件已经上架官方appstore，官方server就是不开源的没有办法，但你可以自己反编译。

**Comment by imjonat** [comment]
![image](https://user-images.githubusercontent.com/42567368/57185259-9b6cf800-6efa-11e9-89ec-b8494486d28d.png)
这该咋办呢 这台是日本的vps

**Comment by leeeboo** [comment]
我觉得你应该用浏览器的console看看问题出在哪个地方

**Comment by imjonat** [comment]
![image](https://user-images.githubusercontent.com/42567368/57185394-17683f80-6efd-11e9-89ea-0c5b04d92524.png)
空空如也。。郁闷了，这个list应该是vps去请求
看了vps也没有信息，唉
![image](https://user-images.githubusercontent.com/42567368/57185410-78901300-6efd-11e9-9464-7fba19f4939f.png)
感觉不应该酱紫

**Comment by leeeboo** [comment]
你没有浏览器调试的经验么？应该看network那里呀...................，另外我觉得你应该去问server的作者。你的terminal log没有问题。

**Comment by imjonat** [comment]
emmm……因为我早已看了network那里，所以你让我看console我就真看console了

**Comment by leeeboo** [comment]
我不认为是server程序的问题，我建议你反编译看看这个list是从哪里读的 google jar 反编译 很容易的

**Comment by imjonat** [comment]
又或许。。可能等我板子到了才能显示？emmm。。。待我到单位反编下
我也觉得得看看反编译后的逻辑

**Comment by imjonat** [comment]
我也觉得得看看反编译后的逻辑

**Comment by leeeboo** [comment]
是的....这个server是要连接上板子才能工作的....

**Comment by imjonat** [comment]
emmm...尴尬。

我现在在看外面的装饰板，我觉得打印光栅*2很有必要呀，看了别人的，我发现显示效果好棒，亚克力板还是差点意思（主要是没有光栅）...

这些技术上的基本都会，就想着做个送女朋友，然后为女朋友开发插件（像您开发bilibili这样的）。就是光栅的打印材料不知道选什么材料好，材料上面没经验又没地方问。。。

另外平时也经常做webapi，自己也正好有套在用的telebot，所以对这个项目超级感兴趣（难得找到志同道合的大部队好吧……）~

**Comment by leeeboo** [comment]
单独光栅感觉是不如亚克力的，因为可能有眩光的问题，完美的解决方案是光栅+蒙板。试试看吧

**Comment by imjonat** [comment]
嗯~！蒙版忘说了！ssπ里面说是A3纸 我觉得海星，到时候试试，谢谢您解答~

**Comment by leeeboo** [comment]
不客气
